<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Luga.BuildingBlocks.Client\Luga.BuildingBlocks.Client.csproj" />
    <ProjectReference Include="..\Luga.Modules.Customers.Shared\Luga.Modules.Customers.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.Extensions.Localization" />
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="Refit" />
    <PackageReference Include="Refit.HttpClientFactory" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*.json" />
  </ItemGroup>

</Project>
